
### GET object
GET http://127.0.0.1:8088/app/v0/object/tmp/main.http


### Post file
PUT http://127.0.0.1:8088/app/v0/object/tmp/main.go

< ./main.go

### POST2 file
PUT https://cos.ap-chengdu.myqcloud.com/ops-software-binary-1255440668//tmp/go.mod?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIDxf7uRhZX4LK2A1LwzDBsIRJwHMnycXuV%2F20210913%2Fap-chengdu%2Fs3%2Faws4_request&X-Amz-Date=20210913T164253Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=897a789ccae349c35cb5f0754a30eacb0dadfeb89550ae8f1bf3eaaf4ffd57d8

< ./main.http